pipeline {
    agent any
    tools {
        maven "maven-3.9.7"
    }
    stages {
        stage('Checkout Code') {
            steps {
                // Checkout the code from the repository
                checkout scm
            }
        }

        stage('Build and Test Order Service') {
            steps {
                    // Run Maven build and tests
                    bat 'mvn clean install -DskipTests=false'
            }
        }

        stage('Build Docker Image') {
            steps {
                    // Build the Docker image
                    bat 'docker build -t artistefx/Order-service:latest .'
            }
        }

        stage('Deploy to Minikube') {
            steps {
                script {
                    // Set the KUBECONFIG environment variable to the path of your kubeconfig file
                    env.KUBECONFIG = 'C:\\Users\\HP\\.kube\\config' // Adjust this path as needed

                    // Run kubectl commands
                    bat 'kubectl config view'
                    bat 'kubectl config get-contexts'

                    // Apply Kubernetes manifests
                    bat 'kubectl apply -f kubernetes-manifests/Order-service-deployment.yaml'
                    bat 'kubectl apply -f kubernetes-manifests/Order-service-service.yaml'
                }
            }
        }
    }
}
