name: CI/CD for Customer Service on Minikube (Windows)

on:
  push:
    branches:
      - master
    paths:
      - 'Customer-Service/**'
      - 'kubernetes-manifests/customer-service-deployment.yaml'
      - 'kubernetes-manifests/customer-service-service.yaml'

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Start Minikube
        run: |
          minikube start --driver=docker

      - name: Set Docker Environment for Minikube
        run: |
          echo "Setting up Docker environment variables for Minikube"
          minikube -p minikube docker-env | Invoke-Expression

      - name: Cache Maven Dependencies
        uses: actions/cache@v2
        with:
          path: |
            C:\Users\runneradmin\.m2\repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and Test Customer Service
        working-directory: Customer-Service
        run: |
          mvn clean install -DskipTests=false

      - name: Build Docker Image for Customer Service
        run: |
          docker build -t customer-service:latest ./Customer-Service

      - name: Deploy Customer Service to Minikube
        run: |
          kubectl apply -f kubernetes-manifests/customer-service-deployment.yaml
          kubectl apply -f kubernetes-manifests/customer-service-service.yaml
