name: CI/CD for Customer Service

on:
  push:
    branches:
      - master
    paths:
      - 'Customer-Service/**'
      - 'kubernetes-manifests/customer-service-deployment.yaml'
      - 'kubernetes-manifests/customer-service-service.yaml'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    env:
      REGISTRY: localhost:5000  # Use a local Docker registry
      K8S_NAMESPACE: default      # Replace with your Kubernetes namespace

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Check Docker Version
        run: docker --version

      - name: Set up Kubeconfig Directory
        run: |
          mkdir $HOME\.kube

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME\.kube\config

      #- name: Log in to Docker Registry
      #  uses: docker/login-action@v2
      #  with:
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Test Customer Service
        working-directory: customer-service
        run: |
          mvn clean install -DskipTests=false

      - name: Print Docker Tag
        run: |
          echo "Docker Tag: $($env:REGISTRY)/customer-service:latest"

      - name: Build Docker Image
        run: |
          docker build -t "$($env:REGISTRY)/customer-service:latest" ./Customer-Service

      - name: Push Docker Image to Minikube
        run: |
          # Push the image to Minikube's Docker daemon (optional)
          docker tag $REGISTRY/customer-service:latest customer-service:latest
          docker push customer-service:latest

      - name: Deploy to Minikube
        env:
          KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          kubectl apply -f kubernetes-manifests/customer-service-deployment.yaml
          kubectl apply -f kubernetes-manifests/customer-service-service.yaml
